version: '3.8'

services:
  web:
    build: .
    container_name: surf-log
    command: uvicorn app.main:app --host 0.0.0.0 --log-level info --reload
    volumes:
      - .:/opt/magda
    ports:
      - 8008:8000
